topic:
  messages: chat_messages.v2
  chats: chats.v2
server:
  port: 9000
spring:
  kafka:
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
      transaction-id-prefix: spring-agent
      properties:
        schema.registry.url: http://localhost:8081
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: spring-client
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.json.KafkaJsonSchemaDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed
        schema.registry.url: http://localhost:8081

